name: "Build, Push, and Scan Super Mario Image"

on:
    push:
        branches:
            - master

env:
    VERSION: ${{ github.run_number }}

jobs:
    build_push_supermario_docker_image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Build and Push Docker Image
              run: |
                  docker build -t docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }} .
                  docker push docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }}

    run_container_image_scan_on_supermario_docker_image:
        runs-on: ubuntu-latest
        needs: build_push_supermario_docker_image

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Get Docker Image from Docker Hub
              run: |
                  docker pull docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }}
                  docker save -o supermariolatestdockerimage.tar docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }}

            - name: Run Trivy vulnerability scanner in tarball mode
              uses: aquasecurity/trivy-action@master
              with:
                  input: supermariolatestdockerimage.tar
                  exit-code: "0"
                  severity: "CRITICAL,HIGH"

    sonarqube_sast_scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    update_k8s_yaml_version_file_with_latest_image_tag:
        runs-on: ubuntu-latest
        needs: run_container_image_scan_on_supermario_docker_image

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Set Git Config
              run: |
                  git config --global user.email "${{ secrets.GIT_EMAIL }}"
                  git config --global user.name "${{ secrets.GIT_USERNAME }}"

            - name: Update Deployment YAML
              run: |
                  git pull
                  sed -i "s|image: docker.io/sedemgarr/training-repo:mario-game-.*$|image: docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }}|" deployment.yaml
                  echo ${{ env.VERSION }} > version.txt
                  CURRENT_VERSION=$(cat version.txt)
                  git add deployment.yaml version.txt
                  git commit -m "Updated deployment yaml and version txt file with supermario image tag to ${CURRENT_VERSION}"
                  git push
