name: "Build, Push, and Scan Super Mario Image"

on:
    push:
        branches:
            - master

env:
    VERSION: ${{ github.run_number }}

jobs:
    sonarqube_sast_scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for better analysis relevance

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build_push_supermario_docker_image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Build and Push Docker Image
              run: |
                  docker build -t docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }} .
                  docker push docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }}

    run_container_image_scan_on_supermario_docker_image:
        runs-on: ubuntu-latest
        needs: build_push_supermario_docker_image

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Get Docker Image from Docker Hub
              run: |
                  docker pull docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }}
                  docker save -o supermariolatestdockerimage.tar docker.io/sedemgarr/training-repo:mario-game-${{ env.VERSION }}

            - name: Run Trivy vulnerability scanner in tarball mode
              uses: aquasecurity/trivy-action@master
              with:
                  input: supermariolatestdockerimage.tar
                  exit-code: "0"
                  severity: "CRITICAL,HIGH"
